{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  labels:
    app: {{ include "common.names.fullname" . }}
  name: {{ include "common.names.fullname" . }}
spec:
  #host: {{ .Values.route.customHost }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  to:
    kind: Service
    name: {{ include "common.names.fullname" . }}
    weight: 100
  {{- if .Values.route.secure }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  {{- end }}
{{- end }}